name: "Dispatch & follow workflow"
description: |
  Dispatches given workflow and watches for its completion, sets status accordingly to the watched workflow
  Requires: curl, jq, sed & GITHUB_TOKEN env
inputs:
  run-name:
    description: "Will be used in combination with datetime to identify the dispatched run and is visible in the ui"
    required: true
  workflow-locator:
    description: |
      The workflow file path in the repository to dispatch
      Format: `<repo-owner>/<repo-name>/actions/workflows/<file>.yaml`
    required: true
  workflow-inputs:
    description: |
      The inputs to pass to the dispatched workflow
      Format: `{"input1": "value1", "input2": "value2"}`
    required: false
    default: "{}"
  workflow-timeout-attempts:
    description: "How many pool calls will be made before considering workflow as timeout-ed"
    required: false
    default: "50"
  workflow-timeout-threshold:
    description: "How many seconds between poll calls"
    required: false
    default: "10"

branding: 
  icon: "eye"
  color: "red"

runs:
  using: "composite"
  steps:
  - run: "./action.sh"  
    shell: bash
    env:
      INPUT_RUN_NAME: ${{ inputs.run-name }}
      INPUT_WORKFLOW_LOCATOR: ${{ inputs.workflow-locator }}
